// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FraudUIClient is the client API for FraudUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FraudUIClient interface {
	// ListEngineSpecs returns a list of Fraud Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (FraudUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type fraudUIClient struct {
	cc grpc.ClientConnInterface
}

func NewFraudUIClient(cc grpc.ClientConnInterface) FraudUIClient {
	return &fraudUIClient{cc}
}

func (c *fraudUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (FraudUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &FraudUI_ServiceDesc.Streams[0], "/v1.FraudUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &fraudUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FraudUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type fraudUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *fraudUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fraudUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.FraudUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FraudUIServer is the server API for FraudUI service.
// All implementations must embed UnimplementedFraudUIServer
// for forward compatibility
type FraudUIServer interface {
	// ListEngineSpecs returns a list of Fraud Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, FraudUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedFraudUIServer()
}

// UnimplementedFraudUIServer must be embedded to have forward compatible implementations.
type UnimplementedFraudUIServer struct {
}

func (UnimplementedFraudUIServer) ListEngineSpecs(*ListEngineSpecsRequest, FraudUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedFraudUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedFraudUIServer) mustEmbedUnimplementedFraudUIServer() {}

// UnsafeFraudUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FraudUIServer will
// result in compilation errors.
type UnsafeFraudUIServer interface {
	mustEmbedUnimplementedFraudUIServer()
}

func RegisterFraudUIServer(s grpc.ServiceRegistrar, srv FraudUIServer) {
	s.RegisterService(&FraudUI_ServiceDesc, srv)
}

func _FraudUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FraudUIServer).ListEngineSpecs(m, &fraudUIListEngineSpecsServer{stream})
}

type FraudUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type fraudUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *fraudUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FraudUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraudUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.FraudUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraudUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FraudUI_ServiceDesc is the grpc.ServiceDesc for FraudUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FraudUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.FraudUI",
	HandlerType: (*FraudUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _FraudUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _FraudUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fraud-ui.proto",
}
